/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regular.validateError;

import com.lhs.taxcpcv2.bean.Assessment;

/**
 *
 * @author gaurav.khanzode
 */
public class SalaryErrorDetailsDB {

    public String salaryErrorDataQuery(String l_client_code, String l_entity_code, String l_error_code, Assessment asmt, int l_record_MNL, int l_record_MXL) {
        String l_query
                //                = "select *\n"
                //                + "  from (select rownum slno,\n"
                //                + "               client_code,\n"
                //                + "               bank_branch_code,\n"
                //                + "               rowid_seq,\n"
                //                + "               deductee_code,\n"
                //                + "               deductee_name,\n"
                //                + "               deductee_panno,\n"
                //                + "               tran_amt,\n"
                //                + "               identification_no,\n"
                //                + "               from_date,\n"
                //                + "               to_date,\n"
                ////                + "               sex,\n"
                //                + "               deduction_ref_no,\n"
                //                + "               calc_tds_amt,\n"
                //                + "               diff_tds_amt,\n"
                //                + "               uptolq_diff_tds_amt\n"
                //                + "          from (select a.client_code,\n"
                //                + "                       w1.bank_branch_code,\n"
                //                + "                       v.rowid_seq,\n"
                //                + "                       a.deductee_code,\n"
                //                + "                       a.deductee_name,\n"
                //                + "                       a.deductee_panno,\n"
                //                + "                       a.tran_amt,\n"
                //                + "                       identification_no,\n"
                //                + "                       to_char(v.from_date, 'dd-mm-rrrr') from_date,\n"
                //                + "                       to_char(v.to_date, 'dd-mm-rrrr') to_date,\n"
                ////                + "                       v.SEX,\n"
                //                + "                       '' deduction_ref_no,\n"
                //                + "                       nvl(calc_tds_amt, 0) calc_tds_amt,\n"
                //                + "                       nvl(diff_tds_amt, 0) diff_tds_amt,\n"
                //                + "                       nvl(lhs_tds_error_n.lhssys_is_short_deduction(a.entity_code,\n"
                //                + "                                                                   a.client_code,\n"
                //                + "                                                                   a.acc_year,\n"
                //                + "                                                                   a.quarter_no,\n"
                //                + "                                                                   a.tds_type_code,\n"
                //                + "                                                                   a.tds_code,\n"
                //                + "                                                                   a.deductee_panno,\n"
                //                + "                                                                   'UPTOLQ_CALC_TDS_AMT_DIFF'),\n"
                //                + "                           0) uptolq_diff_tds_amt\n"
                //                + "                  from VIEW_SALARY_TRAN_LOAD    v,\n"
                //                + "                       tran_load_error_part2_temp a,\n"
                //                + "                       client_mast                w1\n"
                //                + "                 where a.entity_code = '" + l_entity_code + "'\n"
                //                + "                   and v.acc_year = a.acc_year\n"
                //                + "                   and v.entity_code = a.entity_code\n"
                //                + "                   and v.client_code = a.client_code\n"
                ////                + "                   and v.deductee_code = a.deductee_code\n"
                //                + "                   and v.DEDUCTEE_PANNO = a.deductee_panno\n"
                //                + "                   and v.deductee_name = a.deductee_name\n"
                //                + "                   and w1.entity_code = a.entity_code\n"
                //                + "                   and w1.client_code = a.client_code\n"
                //                + "                   and (w1.client_code = '" + l_client_code + "' or\n"
                //                + "                       w1.parent_code = '" + l_client_code + "' or\n"
                //                + "                       w1.g_parent_code = '" + l_client_code + "' or\n"
                //                + "                       w1.sg_parent_code = '" + l_client_code + "' or\n"
                //                + "                       w1.ssg_parent_code = '" + l_client_code + "' or\n"
                //                + "                       w1.sssg_parent_code = '" + l_client_code + "')\n"
                //                + "                   and a.acc_year = '" + asmt.getAccYear() + "'\n"
                //                + "                   and a.quarter_no = '" + asmt.getQuarterNo() + "'\n"
                //                + "                   and a.tds_type_code = '" + asmt.getTdsTypeCode() + "'\n"
                //                + "                   and a.error_code = '" + l_error_code + "'\n"
                //                + "                 order by deductee_panno))\n"
                //                + " where slno between " + l_record_MNL + " and " + l_record_MXL + "";

                /**
                 * New query for salary error data
                 */
                = "select *\n"
                + "  from (select "
//                + "--a.entity_code,\n"
                + "         rownum slno,\n"
                + "         a.client_code,\n"
                + "         w1.bank_branch_code,\n"
                + "         a.deductee_code,\n"
                + "         a.deductee_name,\n"
                + "         a.deductee_panno,\n"
//                + "         --       a.tran_amt,\n"
                + "         nvl(v.afgr4_total_amt, 0) total_taxble_income,\n"
                + "         nvl(v.afg30_total_amt, 0) tax_before_adj,\n"
                + "         nvl(v.afg35_rus_amt, 0) + nvl(v.afg40_itr_amt, 0) rebate_and_refile,\n"
                + "         nvl(v.afgr5_total_amt, 0) net_income_tax_payble,\n"
                + "         nvl(v.afg45_total_amt, 0) total_tds_amt,\n"
                + "         nvl(v.afg46_total_amt, 0) short_fall,\n"
                + "         to_char(v.from_date, 'dd-mm-rrrr') from_date,\n"
                + "         to_char(v.to_date, 'dd-mm-rrrr') to_date,\n"
                + "         '' deduction_ref_no\n"
                + "          from VIEW_SALARY_TRAN_LOAD      v,\n"
                + "               tran_load_error_part2_temp a,\n"
                + "               client_mast                w1\n"
                + "         where a.entity_code = '" + l_entity_code + "'\n"
                + "           and v.acc_year = a.acc_year\n"
                + "           and v.entity_code = a.entity_code\n"
                + "           and v.client_code = a.client_code\n"
                + "           and v.DEDUCTEE_PANNO = a.deductee_panno\n"
                + "           and v.deductee_name = a.deductee_name\n"
                + "           and v.deductee_code = a.deductee_code\n"
                + "           and w1.entity_code = a.entity_code\n"
                + "           and w1.client_code = a.client_code\n"
                + "           and (w1.client_code = '" + l_client_code + "' or w1.parent_code = '" + l_client_code + "' or\n"
                + "               w1.g_parent_code = '" + l_client_code + "' or w1.sg_parent_code = '" + l_client_code + "' or\n"
                + "               w1.ssg_parent_code = '" + l_client_code + "' or\n"
                + "               w1.sssg_parent_code = '" + l_client_code + "')\n"
                + "           and a.acc_year = '" + asmt.getAccYear() + "'\n"
                + "           and a.quarter_no = '" + asmt.getQuarterNo() + "'\n"
                + "           and a.tds_type_code = '" + asmt.getTdsTypeCode() + "'\n"
                + "           and a.error_code = '" + l_error_code + "')\n"
                + " where slno between " + l_record_MNL + " and " + l_record_MXL + "";
        return l_query;
    }//end method

    public String salaryErrorDataCountQuery(String l_client_code, String l_entity_code, String l_error_code, Assessment asmt) {
        String l_query 
//                = "select count(*)\n"
//                + "  from (select a.client_code,\n"
//                + "               w1.bank_branch_code,\n"
//                + "               a.deductee_code,\n"
//                + "               a.deductee_name,\n"
//                + "               a.deductee_panno,\n"
//                + "               a.tran_amt,\n"
//                + "               to_char(v.from_date, 'dd-mm-rrrr') from_date,\n"
//                + "               to_char(v.to_date, 'dd-mm-rrrr') to_date,\n"
//                //                + "               v.SEX,\n"
//                + "               '' deduction_ref_no\n"
//                + "          from VIEW_SALARY_TRAN_LOAD    v,\n"
//                + "               tran_load_error_part2_temp a,\n"
//                + "               client_mast                w1\n"
//                + "         where a.entity_code = '" + l_entity_code + "'\n"
//                + "           and v.acc_year = a.acc_year\n"
//                + "           and v.entity_code = a.entity_code\n"
//                + "           and v.client_code = a.client_code\n"
//                //                + "           and v.deductee_code = a.deductee_code\n"
//                + "           and v.DEDUCTEE_PANNO = a.deductee_panno\n"
//                + "           and v.deductee_name = a.deductee_name\n"
//                + "           and w1.entity_code = a.entity_code\n"
//                + "           and w1.client_code = a.client_code\n"
//                + "           and (w1.client_code = '" + l_client_code + "' or w1.parent_code = '" + l_client_code + "' or\n"
//                + "               w1.g_parent_code = '" + l_client_code + "' or\n"
//                + "               w1.sg_parent_code = '" + l_client_code + "' or\n"
//                + "               w1.ssg_parent_code = '" + l_client_code + "' or\n"
//                + "               w1.sssg_parent_code = '" + l_client_code + "')\n"
//                + "           and a.acc_year = '" + asmt.getAccYear() + "'\n"
//                + "           and a.quarter_no = '" + asmt.getQuarterNo() + "'\n"
//                + "           and a.tds_type_code = '" + asmt.getTdsTypeCode() + "'\n"
//                + "           and a.error_code = '" + l_error_code + "')";
                
                ="select count(*)\n"
                + "  from (select "
//                + "--a.entity_code,\n"
                + "         rownum slno,\n"
                + "         a.client_code,\n"
                + "         w1.bank_branch_code,\n"
                + "         a.deductee_code,\n"
                + "         a.deductee_name,\n"
                + "         a.deductee_panno,\n"
//                + "         --       a.tran_amt,\n"
                + "         nvl(v.afgr4_total_amt, 0) total_taxble_income,\n"
                + "         nvl(v.afg30_total_amt, 0) tax_before_adj,\n"
                + "         nvl(v.afg35_rus_amt, 0) + nvl(v.afg40_itr_amt, 0) rebate_and_refile,\n"
                + "         nvl(v.afgr5_total_amt, 0) net_income_tax_payble,\n"
                + "         nvl(v.afg45_total_amt, 0) total_tds_amt,\n"
                + "         nvl(v.afg46_total_amt, 0) short_fall,\n"
                + "         to_char(v.from_date, 'dd-mm-rrrr') from_date,\n"
                + "         to_char(v.to_date, 'dd-mm-rrrr') to_date,\n"
                + "         '' deduction_ref_no\n"
                + "          from VIEW_SALARY_TRAN_LOAD      v,\n"
                + "               tran_load_error_part2_temp a,\n"
                + "               client_mast                w1\n"
                + "         where a.entity_code = '" + l_entity_code + "'\n"
                + "           and v.acc_year = a.acc_year\n"
                + "           and v.entity_code = a.entity_code\n"
                + "           and v.client_code = a.client_code\n"
                + "           and v.DEDUCTEE_PANNO = a.deductee_panno\n"
                + "           and v.deductee_name = a.deductee_name\n"
                + "           and v.deductee_code = a.deductee_code\n"
                + "           and w1.entity_code = a.entity_code\n"
                + "           and w1.client_code = a.client_code\n"
                + "           and (w1.client_code = '" + l_client_code + "' or w1.parent_code = '" + l_client_code + "' or\n"
                + "               w1.g_parent_code = '" + l_client_code + "' or w1.sg_parent_code = '" + l_client_code + "' or\n"
                + "               w1.ssg_parent_code = '" + l_client_code + "' or\n"
                + "               w1.sssg_parent_code = '" + l_client_code + "')\n"
                + "           and a.acc_year = '" + asmt.getAccYear() + "'\n"
                + "           and a.quarter_no = '" + asmt.getQuarterNo() + "'\n"
                + "           and a.tds_type_code = '" + asmt.getTdsTypeCode() + "'\n"
                + "           and a.error_code = '" + l_error_code + "')\n";

        return l_query;
    }//end method
}//end class
