/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form15GH.transaction;

import com.lhs.taxcpcv2.bean.Assessment;
import globalUtilities.Util;
import hibernateObjects.UserMast;
import hibernateObjects.ViewClientMast;

/**
 *
 * @author aniket.naik
 */
public class Form15GHDB {

    public String getDeducteeMast15GHCountQuery(String client_code, String entity_code, Assessment asmt, String pan_filter, String dname_filter, String vffilter, String invGF_filter, String incompAmt_filter, String unino_filter, String custid_filter) {

        String deductee15ghQuery = "select count(*)\n"
                + "  from (select rownum slno,\n"
                + "               t.entity_code,\n"
                + "               t.client_code,\n"
                + "               t.parent_code,\n"
                + "               '' g_parent_code,\n"
                + "               '' sg_parent_code,\n"
                + "               '' ssg_parent_code,\n"
                + "               '' sssg_parent_code,\n"
                + "               '' bank_branch_code,\n"
                + "               t.deductee_code,\n"
                + "               t.deductee_name,\n"
                + "               t.dob,\n"
                + "               t.remark,\n"
                + "               t.deductee_type_code,\n"
                + "               t.tds_code,\n"
                + "               t.deductee_status,\n"
                + "               t.created_date,\n"
                + "               t.closed_date,\n"
                + "               t.tds_tran_rowid_seq,\n"
                + "               t.website,\n"
                + "               t.add1,\n"
                + "               t.add2,\n"
                + "               t.add3,\n"
                + "               t.add4,\n"
                + "               t.city_code,\n"
                + "               t.state_code,\n"
                + "                       (select g.state_name\n"
                + "                          from state_mast g\n"
                + "                         where g.state_code = t.state_code) state_name,\n"
                + "               t.pin,\n"
                + "               t.stdcode,\n"
                + "               t.phoneno,\n"
                + "               t.mobileno,\n"
                + "               t.email_id,\n"
                + "               t.panno,\n"
                + "               t.name_as_panno,\n"
                + "               t.deductee_panno_valid,\n"
                + "               deductee_panno_verified verifiedby_flag,\n"
                + "                       case\n"
                + "                       when nvl(deductee_panno_verified, '') = 'Y' then\n"
                + "                          'Verified'\n"
                + "                        when nvl(deductee_panno_verified, '') = 'X' then\n"
                + "                          'Invalid'\n"
                + "                         when nvl(deductee_panno_verified, '') = 'N' then\n"
                + "                          'Not Verified'\n"
                + "                         else\n"
                + "                          'Not Available'\n"
                + "                       end verifiedby_flag_name,\n"
                + "               t.tanno,\n"
                + "               t.lastupdate,\n"
                + "               t.flag,\n"
                + "               t.income_status,\n"
                + "               t.resident_status,\n"
                + "               t.certficate_no,\n"
                + "               t.certficate_valid_upto,\n"
                + "               t.identification_no,\n"
                + "               t.company_name,\n"
                + "               t.country_code,\n"
                + "                       (SELECT w.country_name\n"
                + "                          from COUNTRY_MAST w\n"
                + "                         where w.country_code = t.country_code) country_name,\n"
                + "               t.is_transporter,\n"
                + "               t.principle_of_business,\n"
                + "               t.deduction_ref_no,\n"
                + "               t.deductee_catg,\n"
                + "                       (SELECT G.deductee_catg_name\n"
                + "                          FROM VIEW_DEDUCTEE_CATG G\n"
                + "                         WHERE G.deductee_catg_code = T.DEDUCTEE_CATG) deductee_catg_NAME,\n"
                + "               t.join_date,\n"
                + "               t.left_date,\n"
                + "               t.sex,\n"
                + "               t.emp_code,\n"
                + "               t.reference_no,\n"
                + "               t.bflag,\n"
                + "               t.assessed_tax_flag,\n"
                + "               t.latest_assessment_year,\n"
                + "               t.est_declaration_income,\n"
                + "               t.est_total_income,\n"
                + "               t.total_no_form,\n"
                + "               t.aggregate_income_amt,\n"
                + "               t.declaration_date,\n"
                + "               t.income_amount_paid,\n"
                + "               t.income_paid_date,\n"
                + "               t.deductee_ref_code2,\n"
                + "               '' invalid_rec_flag,\n"
                + "               t.acc_year,\n"
                + "               '' pan_status\n"
                + "          from deductee_mast_15gh t ,client_mast cm\n"
                + "         where cm.entity_code = t.entity_code"
                + "            and cm.client_code = t.client_code\n"
                + "           and t.entity_code = '" + entity_code + "'\n"
                + "           and (cm.client_code = '" + client_code + "' Or cm.parent_code='" + client_code + "' OR cm.g_parent_code = '" + client_code + "' or cm.sg_parent_code = '" + client_code + "' OR cm.ssg_parent_code = '" + client_code + "' or cm.sssg_parent_code = '" + client_code + "')\n"
                + "           and t.acc_year = '" + asmt.getAccYear() + "'\n"
                + "           and t.tds_type_code = '" + asmt.getTdsTypeCode() + "'\n"
                + "           and t.quarter_no = '" + asmt.getQuarterNo() + "'"
                + ") t where 1=1 \n"
                + pan_filter + dname_filter + vffilter + invGF_filter + incompAmt_filter + unino_filter + custid_filter;

        utl.generateSpecialLog("15 gh deductee count query: ", deductee15ghQuery);
        return deductee15ghQuery;

    }

    public String get15GHDataGridQuery(Assessment asmt, ViewClientMast clientmast, String pan_filter, String dname_filter, String vffilter, String invGF_filter, String unino_filter, String custid_filter, String incompAmt_filter, int l_record_MXL, int l_record_MNL) {

        String deductee_query = "select *\n"
                + "  from (select rownum slno,\n"
                + "               entity_code,\n"
                + "               client_code,\n"
                + "               parent_code,\n"
                + "               g_parent_code,\n"
                + "               sg_parent_code,\n"
                + "               ssg_parent_code,\n"
                + "               sssg_parent_code,\n"
                + "               bank_branch_code,\n"
                + "               deductee_code,\n"
                + "               deductee_name,\n"
                + "               dob,\n"
                + "               remark,\n"
                + "               deductee_type_code,\n"
                + "               tds_code,\n"
                + "               deductee_status,\n"
                + "               created_date,\n"
                + "               closed_date,\n"
                + "               tds_tran_rowid_seq,\n"
                + "               website,\n"
                + "               add1,\n"
                + "               add2,\n"
                + "               add3,\n"
                + "               add4,\n"
                + "               city_code,\n"
                + "               state_code,\n"
                + "               state_name,\n"
                + "               pin,\n"
                + "               stdcode,\n"
                + "               phoneno,\n"
                + "               mobileno,\n"
                + "               email_id,\n"
                + "               panno,\n"
                + "               name_as_panno,\n"
                + "               deductee_panno_valid,\n"
                + "               verifiedby_flag,\n"
                + "               verifiedby_flag_name,\n"
                + "               tanno,\n"
                + "               lastupdate,\n"
                + "               flag,\n"
                + "               income_status,\n"
                + "               resident_status,\n"
                + "               certficate_no,\n"
                + "               certficate_valid_upto,\n"
                + "               identification_no,\n"
                + "               company_name,\n"
                + "               country_code,\n"
                + "               country_name,\n"
                + "               is_transporter,\n"
                + "               principle_of_business,\n"
                + "               deduction_ref_no,\n"
                + "               deductee_catg,\n"
                + "               deductee_catg_NAME,\n"
                + "               join_date,\n"
                + "               left_date,\n"
                + "               sex,\n"
                + "               emp_code,\n"
                + "               reference_no,\n"
                + "               bflag,\n"
                + "               assessed_tax_flag,\n"
                + "               latest_assessment_year,\n"
                + "               est_declaration_income,\n"
                + "               est_total_income,\n"
                + "               total_no_form,\n"
                + "               aggregate_income_amt,\n"
                + "               declaration_date,\n"
                + "               income_amount_paid,\n"
                + "               income_paid_date,\n"
                + "               deductee_ref_code2,\n"
                + "               invalid_rec_flag,\n"
                + "               acc_year,\n"
                + "               pan_status,\n"
                + "               rowid_seq\n"
                + "from (select \n"
                + "               t.entity_code,\n"
                + "               t.client_code,\n"
                + "               t.parent_code,\n"
                + "               '' g_parent_code,\n"
                + "               '' sg_parent_code,\n"
                + "               '' ssg_parent_code,\n"
                + "               '' sssg_parent_code,\n"
                + "               bank_branch_code,\n"
                + "               t.deductee_code,\n"
                + "               t.deductee_name,\n"
                + "               t.dob,\n"
                + "               t.remark,\n"
                + "               t.deductee_type_code,\n"
                + "               t.tds_code,\n"
                + "               t.deductee_status,\n"
                + "               t.created_date,\n"
                + "               t.closed_date,\n"
                + "               t.tds_tran_rowid_seq,\n"
                + "               t.website,\n"
                + "               t.add1,\n"
                + "               t.add2,\n"
                + "               t.add3,\n"
                + "               t.add4,\n"
                + "               t.city_code,\n"
                + "               t.state_code,\n"
                + "                       (select g.state_name\n"
                + "                          from state_mast g\n"
                + "                         where g.state_code = t.state_code) state_name,\n"
                + "               t.pin,\n"
                + "               t.stdcode,\n"
                + "               t.phoneno,\n"
                + "               t.mobileno,\n"
                + "               t.email_id,\n"
                + "               t.panno,\n"
                + "               t.name_as_panno,\n"
                + "               t.deductee_panno_valid,\n"
                + "               deductee_panno_verified verifiedby_flag,\n"
                + "                       case\n"
                + "                       when nvl(deductee_panno_verified, '') = 'Y' then\n"
                + "                          'Verified'\n"
                + "                        when nvl(deductee_panno_verified, '') = 'X' then\n"
                + "                          'Invalid'\n"
                + "                         when nvl(deductee_panno_verified, '') = 'N' then\n"
                + "                          'Not Verified'\n"
                + "                         else\n"
                + "                          'Not Available'\n"
                + "                       end verifiedby_flag_name,\n"
                + "               t.tanno,\n"
                + "               t.lastupdate,\n"
                + "               t.flag,\n"
                + "               t.income_status,\n"
                + "               t.resident_status,\n"
                + "               t.certficate_no,\n"
                + "               t.certficate_valid_upto,\n"
                + "               t.identification_no,\n"
                + "               t.company_name,\n"
                + "               t.country_code,\n"
                + "                       (SELECT w.country_name\n"
                + "                          from COUNTRY_MAST w\n"
                + "                         where w.country_code = t.country_code) country_name,\n"
                + "               t.is_transporter,\n"
                + "               t.principle_of_business,\n"
                + "               t.deduction_ref_no,\n"
                + "               t.deductee_catg,\n"
                + "                       (SELECT G.deductee_catg_name\n"
                + "                          FROM VIEW_DEDUCTEE_CATG G\n"
                + "                         WHERE G.deductee_catg_code = T.DEDUCTEE_CATG) deductee_catg_NAME,\n"
                + "               t.join_date,\n"
                + "               t.left_date,\n"
                + "               t.sex,\n"
                + "               t.emp_code,\n"
                + "               t.reference_no,\n"
                + "               t.bflag,\n"
                + "               t.assessed_tax_flag,\n"
                + "               t.latest_assessment_year,\n"
                + "               t.est_declaration_income,\n"
                + "               t.est_total_income,\n"
                + "               t.total_no_form,\n"
                + "               t.aggregate_income_amt,\n"
                + "               t.declaration_date,\n"
                + "               t.income_amount_paid,\n"
                + "               t.income_paid_date,\n"
                + "               t.deductee_ref_code2,\n"
                + "               '' invalid_rec_flag,\n"
                + "               t.acc_year,\n"
                + "               '' pan_status,\n"
                + "               t.rowid_seq\n"
                + "          from deductee_mast_15gh t,client_mast cm\n"
                + "         where cm.entity_code = t.entity_code"
                + "            and cm.client_code = t.client_code\n"
                + "           and t.entity_code = '" + clientmast.getEntity_code() + "'\n"
                + "           and (cm.client_code = '" + clientmast.getClient_code() + "' Or cm.parent_code='" + clientmast.getClient_code()
                + "' OR cm.g_parent_code = '" + clientmast.getClient_code() + "' or cm.sg_parent_code = '" + clientmast.getClient_code()
                + "' OR cm.ssg_parent_code = '" + clientmast.getClient_code() + "' or cm.sssg_parent_code = '" + clientmast.getClient_code() + "')\n"
                + "           and t.acc_year = '" + asmt.getAccYear() + "'\n"
                + "           and t.tds_type_code = '" + asmt.getTdsTypeCode() + "'\n"
                + "           and t.quarter_no = '" + asmt.getQuarterNo() + "'"
                + "order by rowid_seq)t \nwhere 1=1\n"
                + pan_filter + dname_filter + vffilter + invGF_filter + incompAmt_filter + unino_filter + custid_filter
                + ") \n"
                + " where slno between " + l_record_MNL + " and " + l_record_MXL + "";

        utl.generateSpecialLog("15 gh deductee_query: ", deductee_query);
        return deductee_query;

    }

    public String getUpdateQuery(ViewClientMast client, Long rowid_seq) {

        String query = "update deductee_mast_15gh a set a.deductee_panno_verified=(select lhs_utility.is_panno_verified(a.panno) from dual),\n"
                + "a.deductee_panno_valid=(select lhs_utility.is_valid_panno(a.panno) from dual),\n"
                + "a.name_as_panno=(select lhs_utility.get_name('panmast_name',panno) from dual)\n"
                + "where entity_code='" + client.getEntity_code() + "'\n"
                + "and nvl(deductee_panno_verified,'N')<>'Y'\n"
                + "and rowid_seq = '" + rowid_seq + "'\n"
                + "and   exists (select 1\n"
                + "              from   client_mast b\n"
                + "              where  b.client_code=a.client_code\n"
                + "              and    (b.client_code = '" + client.getClient_code() + "' or b.parent_code = '" + client.getClient_code() + "' or\n"
                + "                      b.g_parent_code = '" + client.getClient_code() + "' or b.sg_parent_code = '" + client.getClient_code() + "' or\n"
                + "                      b.ssg_parent_code = '" + client.getClient_code() + "' or b.sssg_parent_code = '" + client.getClient_code() + "')\n"
                + " )";

        return query;

    }

    public String getClientGroupListQuery(ViewClientMast client, Assessment asmt, UserMast user, int loginLevel) {

        String query = "SELECT client_code,client_name ,is_client_login_level,client_level_type ,bank_branch_code FROM  (select '" + client.getEntity_code() + "' entity_code,\n"
                + "       '" + asmt.getAccYear() + "' acc_year,\n"
                + "       '" + asmt.getQuarterNo() + "' quarter_no,\n"
                + "       '" + asmt.getTdsTypeCode() + "' tds_type_code,\n"
                + "       a.client_code,\n"
                + "       a.client_name,\n"
                + "       a.tanno,\n"
                + "       a.bank_branch_code, A.is_client_login_level ,A.client_level_type \n"
                + "       from   client_mast a\n"
                + "where  entity_code='" + client.getEntity_code() + "'\n"
                + "and    ((" + loginLevel + " =0   and code_level=" + client.getCode_level() + " /*Login client code level*/) or\n"
                + "       (" + loginLevel + " =1  and code_level=" + (Integer.parseInt(client.getCode_level()) + 1) + " /*Login client code level + 1*/)\n"
                + "       )\n"
                + "and   (a.client_code = '" + client.getClient_code() + "' or\n"
                + "       a.parent_code = '" + client.getClient_code() + "' or\n"
                + "       a.g_parent_code = '" + client.getClient_code() + "' or\n"
                + "       a.sg_parent_code = '" + client.getClient_code() + "' or\n"
                + "       a.ssg_parent_code = '" + client.getClient_code() + "' or\n"
                + "       a.sssg_parent_code = '" + client.getClient_code() + "'\n"
                + "      ) )";
        return query;

    }
//    public String getClientGroupListQuery(String login_entity_code, String login_client_code) {
//
//        String query = "select *\n"
//                + "  from (select client_code,\n"
//                + "               client_name,\n"
//                + "               is_client_login_level,\n"
//                + "               client_level_type\n"
//                + "          from (select client_code,\n"
//                + "                       rownum slno,\n"
//                + "                       client_name,\n"
//                + "                       parent_code,\n"
//                + "                       is_client_login_level,\n"
//                + "                       client_level_type\n"
//                + "                  from view_client_mast t\n"
//                + "                 where t.entity_code = '" + login_entity_code + "'\n"
//                + "                 START WITH CLIENT_code = '" + login_client_code + "'\n"
//                + "                connect by prior client_code = parent_code\n"
//                + "                 ORDER SIBLINGS BY lastupdate desc) t\n"
//                + "         order by slno)";
//        utl.generateLog("query..."+query);
//        return query;
//
//    }

    public String getClientMastFunctionQuery(String entity_code, String client_code, String accYear, String Bflag, String tdsTypeCode) {

        String functionString
                = " select nvl(max(SUBSTR(t.reference_no,2,10)),'0')refrance_no\n"
                + "  from deductee_mast_15gh t\n"
                + " where t.entity_code = '" + entity_code + "'\n"
                + "   and t.acc_year = '" + accYear + "'\n"
                + "   and t.tds_type_code = '" + tdsTypeCode + "'\n"
                + "   and t.bflag = '" + Bflag + "'\n"
                + "   and exists\n"
                + " (select 1\n"
                + "          from client_mast w1\n"
                + "         where w1.client_code = t.client_code\n"
                + "           and (w1.client_code = '" + client_code + "' or w1.parent_code = '" + client_code + "' or\n"
                + "               w1.g_parent_code = '" + client_code + "' or\n"
                + "               w1.sg_parent_code = '" + client_code + "' or\n"
                + "               w1.ssg_parent_code = '" + client_code + "' or\n"
                + "               w1.sssg_parent_code = '" + client_code + "'))";

        return functionString;

    }

    public String getRefNoDtlQuery(String entity_code, String accYear, String quarterNo, String tdsTypeCode, Long l_client_loginid_seq, String genClientCode) {

        String query = "select client_code,\n"
                + "       bank_branch_code,\n"
                + "       client_name,\n"
                + "       tanno,\n"
                + "       lpad(nvl(last_gen_15g, '0'),9,0) last_gen_15g,\n"
                + "       lpad(nvl(last_gen_15h, '0'),9,0) last_gen_15h,\n"
                + "       lpad(nvl(next_gen_15g, ''),9,0) next_gen_15g,\n"
                + "       lpad(nvl(next_gen_15h, ''),9,0) next_gen_15h\n"
                + "  from (select t.col2  client_code,\n"
                + "               t.col11 bank_branch_code,\n"
                + "               t.col12 client_name,\n"
                + "               t.col13 tanno,\n"
                + "               t.col14 last_gen_15g,\n"
                + "               t.col15 last_gen_15h,\n"
                + "               t.col16 next_gen_15g,\n"
                + "               t.col17 next_gen_15h\n"
                + "          from temp_data t\n"
                + "         where t.col1 = '" + entity_code + "'\n"
                + "           and t.col3 = '" + accYear + "'\n"
                + "           and t.col5 = '" + quarterNo + "'\n"
                + "           and t.col8 = '" + tdsTypeCode + "'\n"
                + "           and t.col9 = '" + l_client_loginid_seq + "'\n"
                + "           and t.col100 = 'Deductee15GHRefNo'\n"
                + "           and exists (select 1\n"
                + "                  from client_mast w1\n"
                + "                 where w1.client_code = t.col2\n"
                + "                   and (w1.client_code = '" + genClientCode + "' or\n"
                + "                       w1.parent_code = '" + genClientCode + "' or\n"
                + "                       w1.g_parent_code = '" + genClientCode + "' or\n"
                + "                       w1.sg_parent_code = '" + genClientCode + "' or\n"
                + "                       w1.ssg_parent_code = '" + genClientCode + "' or\n"
                + "                       w1.sssg_parent_code = '" + genClientCode + "'))\n"
                + "         order by t.col2)";

        return query;

    }

    public String show15GHReferanceNoDetail(String entity_code, String accYear, String quarterNo, String tdsTypeCode, String clientCode, String filterFlag, int loginFlag, String codeLevel, String loginClientCode) {
        String refno_dtl_query = "";
        try {

//            refno_dtl_query = "select entity_code,client_code,\n"
//                    + "         lhs_utility.get_name('client_code',client_code)client_name,\n"
//                    + "         tanno,\n"
//                    + "         bank_branch_code,\n"
//                    + "         lpad(last_gen_15g,9,0)last_gen_15g,\n"
//                    + "         lpad(last_gen_15h,9,0)last_gen_15h,\n"
//                    + "         lpad(next_gen_15g,9,0)next_gen_15g,\n"
//                    + "         lpad(next_gen_15h,9,0)next_gen_15h\n"
//                    + "    from (select a.entity_code,\n"
//                    + "                 a.client_code,\n"
//                    + "                 a.client_name,\n"
//                    + "                 a.tanno,\n"
//                    + "                 a.bank_branch_code,\n"
//                    + "                 g15_flag,\n"
//                    + "                 nvl(g15_max_no,'0')last_gen_15g,\n"
//                    + "                 'H' h15_flag,\n"
//                    + "                 nvl(h15_max_no,'0')last_gen_15h,\n"
//                    + "                 (nvl(g15_max_no,'0') + 1) next_gen_15g,\n"
//                    + "                 (nvl(h15_max_no,'0') + 1) next_gen_15h\n"
//                    + "            from (\n"
//                    + "            select distinct a.entity_code,\n"
//                    + "                         a.client_code,\n"
//                    + "                         b.client_name,\n"
//                    + "                         a.tanno,\n"
//                    + "                         b.bank_branch_code,\n"
//                    + "                         'G' g15_flag,\n"
//                    + "                         (select to_number(max(substr(reference_no, 2)))\n"
//                    + "                            from deductee_mast_15gh b\n"
//                    + "                           where b.entity_code = a.entity_code\n"
//                    + "                             and b.client_code = a.client_code\n"
//                    + "                             and bflag = 'B'\n"
//                    + "                             and b.entity_code = '" + entity_code + "'\n"
//                    + "                             and b.acc_year = '" + accYear + "'\n"
//                    //                    + "                             and b.quarter_no = '" + quarterNo + "'\n"
//                    + "                             and b.tds_type_code = '" + tdsTypeCode + "') g15_max_no,\n"
//                    + "                         'H' h15_flag,\n"
//                    + "                         (select to_number(max(substr(reference_no, 2)))\n"
//                    + "                          from   deductee_mast_15gh b\n"
//                    + "                          where b.entity_code = a.entity_code\n"
//                    + "                             and b.client_code = a.client_code\n"
//                    + "                             and bflag = 'D'\n"
//                    + "                             and b.entity_code = a.entity_code\n"
//                    + "                             and b.acc_year = a.acc_year\n"
//                    //                    + "                             and b.quarter_no = a.quarter_no\n"
//                    + "                             and b.tds_type_code = '" + tdsTypeCode + "') h15_max_no\n"
//                    + "                    from  deductee_mast_15gh a, client_mast b\n"
//                    + "                    where a.entity_code=b.entity_code\n"
//                    + "                    and   a.client_code=b.client_code\n"
//                    + "                    and   a.acc_year='" + accYear + "'\n"
//                    //                    + "                    and   a.quarter_no='" + quarterNo + "'\n"
//                    + "                    and   a.tds_type_code='" + tdsTypeCode + "'\n"
//                    + "                    and   (b.client_code = '" + clientCode + "' or\n"
//                    + "                           b.parent_code = '" + clientCode + "' or\n"
//                    + "                           b.g_parent_code = '" + clientCode + "' or\n"
//                    + "                           b.sg_parent_code = '" + clientCode + "' or\n"
//                    + "                           b.ssg_parent_code = '" + clientCode + "' or\n"
//                    + "                           b.sssg_parent_code = '" + clientCode + "')\n"
//                    + "                    ) a\n"
//                    + "           order by a.bank_branch_code)";
            refno_dtl_query = "select a.entity_code,\n"
                    + "       a.client_code,\n"
                    + "       a.client_name,\n"
                    + "       a.tanno,\n"
                    + "       a.bank_branch_code,\n"
                    + "       lpad(a.last_gen_15g,9,0)last_gen_15g,\n"
                    + "       lpad(a.last_gen_15h,9,0)last_gen_15h,\n"
                    + "       lpad(a.next_gen_15g,9,0)next_gen_15g,\n"
                    + "       lpad(a.next_gen_15h,9,0)next_gen_15h\n"
                    + "from   (select a.entity_code,\n"
                    + "               a.client_code,\n"
                    + "               a.client_name,\n"
                    + "               a.tanno,\n"
                    + "               a.bank_branch_code,\n"
                    + "               a.g15_flag,\n"
                    + "               nvl(g15_max_no,'0')last_gen_15g,\n"
                    + "               a.h15_flag,\n"
                    + "               nvl(a.h15_max_no,'0')last_gen_15h,\n"
                    + "               (nvl(a.g15_max_no,'0') + 1) next_gen_15g,\n"
                    + "               (nvl(a.h15_max_no,'0') + 1) next_gen_15h\n"
                    + "        from   (select a.entity_code,\n"
                    + "                       a.acc_year,\n"
                    + "                       a.quarter_no,\n"
                    + "                       a.tds_type_code,\n"
                    + "                       a.client_code,\n"
                    + "                       a.client_name,\n"
                    + "                       a.tanno,\n"
                    + "                       a.bank_branch_code,\n"
                    + "                       'G' g15_flag,\n"
                    + "                       (select to_number(max(substr(reference_no, 2)))\n"
                    + "                        from   deductee_mast_15gh b, client_mast c\n"
                    + "                        where  c.entity_code=b.entity_code\n"
                    + "                        and    c.client_code=b.client_code\n"
                    + "                        and    c.entity_code = a.entity_code\n"
                    + "                        and    (c.client_code = a.client_code or\n"
                    + "                                c.parent_code=a.client_code or\n"
                    + "                                c.g_parent_code=a.client_code or\n"
                    + "                                c.sg_parent_code=a.client_code or\n"
                    + "                                c.ssg_parent_code=a.client_code or\n"
                    + "                                c.sssg_parent_code=a.client_code\n"
                    + "                               )\n"
                    + "                        and    b.entity_code = a.entity_code\n"
                    + "                        and    b.acc_year = a.acc_year\n"
                    + "                        and    b.tds_type_code = a.tds_type_code\n"
                    + "                        and    bflag = 'B'\n"
                    + "                        ) g15_max_no,\n"
                    + "                        'H' h15_flag,\n"
                    + "                        (select to_number(max(substr(reference_no, 2)))\n"
                    + "                         from   deductee_mast_15gh b, client_mast c\n"
                    + "                         where  c.entity_code=b.entity_code\n"
                    + "                         and    c.client_code=b.client_code\n"
                    + "                         and    c.entity_code = a.entity_code\n"
                    + "                         and    (c.client_code = a.client_code or\n"
                    + "                                 c.parent_code=a.client_code or\n"
                    + "                                 c.g_parent_code=a.client_code or\n"
                    + "                                 c.sg_parent_code=a.client_code or\n"
                    + "                                 c.ssg_parent_code=a.client_code or\n"
                    + "                                 c.sssg_parent_code=a.client_code\n"
                    + "                                )\n"
                    + "                         and    b.entity_code = a.entity_code\n"
                    + "                         and    b.acc_year = a.acc_year\n"
                    + "                         and    b.tds_type_code = a.tds_type_code\n"
                    + "                         and    bflag = 'D'\n"
                    + "                         ) h15_max_no\n"
                    + "                from    (select '" + entity_code + "' entity_code,\n"
                    + "                                '" + accYear + "' acc_year,\n"
                    + "                                '" + quarterNo + "' quarter_no,\n"
                    + "                                '" + tdsTypeCode + "' tds_type_code,\n"
                    + "                                a.client_code,\n"
                    + "                                a.client_name,\n"
                    + "                                a.tanno,\n"
                    + "                                a.bank_branch_code\n"
                    + "                         from   client_mast a\n"
                    + "                         where  entity_code='" + entity_code + "'\n"
                    + "                         and    ((" + loginFlag + " =0   and code_level=" + codeLevel + " /*Login client code level*/ and client_code='" + loginClientCode + "') or\n"
                    + "                                 (" + loginFlag + " =1  and code_level=" + (Integer.parseInt(codeLevel) + 1) + " /*Login client code level + 1*/)\n"
                    + "                                )\n";

            if (loginFlag != 0) {
                if (utl.isnull(filterFlag) || !filterFlag.equalsIgnoreCase("T")) {
                    refno_dtl_query += "\n"
                            + "                        --FILTER FOR LOGIN LEVEL START\n"
                            + "            and a.client_code<>'" + loginClientCode + "'              and   (a.client_code = '" + clientCode + "' or\n"
                            + "                                a.parent_code = '" + clientCode + "' or\n"
                            + "                                a.g_parent_code = '" + clientCode + "' or\n"
                            + "                                a.sg_parent_code = '" + clientCode + "' or\n"
                            + "                                a.ssg_parent_code = '" + clientCode + "' or\n"
                            + "                                a.sssg_parent_code = '" + clientCode + "'\n"
                            + "                               )\n";

                } else {

                    refno_dtl_query += "\n"
                            + "                    --    FILTER AS PER SELECTED CLIENT FROM LIST BOX START\n"
                            + "                         and   (a.client_code = '" + clientCode + "' or\n"
                            + "                                a.parent_code = '" + clientCode + "' or\n"
                            + "                                a.g_parent_code = '" + clientCode + "' or\n"
                            + "                                a.sg_parent_code = '" + clientCode + "'or\n"
                            + "                                a.ssg_parent_code = '" + clientCode + "' or\n"
                            + "                                a.sssg_parent_code = '" + clientCode + "'\n"
                            + "                               )\n";
                }
            }

            refno_dtl_query += "                         ) a\n"
                    + "                ) a    \n"
                    + "        ) a";

        } catch (Exception e) {
            e.printStackTrace();
        }
        return refno_dtl_query;
    }

    public String getExistingReferenceNoQuery(String genClientCode, String accYear, String entity_code, String quarterNo, String tdsTypeCode, String nextGen15GNo, String Bflag) {

        String functionString
                = "select count(nvl(SUBSTR(t.reference_no, 2, 10), '0')) refranceNoCount\n"
                + "  from deductee_mast_15gh t\n"
                + " where t.entity_code = '" + entity_code + "'\n"
                + "   and t.acc_year = '" + accYear + "'\n"
                + "   and t.quarter_no = '" + quarterNo + "'\n"
                + "   and t.tds_type_code = '" + tdsTypeCode + "'\n"
                + "   and t.bflag = '" + Bflag + "'\n"
                + "   and exists\n"
                + " (select 1\n"
                + "          from client_mast w1\n"
                + "         where w1.client_code = t.client_code\n"
                + "           and (w1.client_code = '" + genClientCode + "' or w1.parent_code = '" + genClientCode + "' or\n"
                + "               w1.g_parent_code = '" + genClientCode + "' or\n"
                + "               w1.sg_parent_code = '" + genClientCode + "' or\n"
                + "               w1.ssg_parent_code = '" + genClientCode + "' or\n"
                + "               w1.sssg_parent_code = '" + genClientCode + "'))\n"
                + "   and t.reference_no = '" + nextGen15GNo + "'";

        return functionString;

    }

    public String getCountReferenceNoDetailQuery(String entity_code, String quarterNo, String acc_year, String tds_type_code, String genClientCode,
            int process_level, int code_level) {

        String query = "select count(*) from ( \n"
                + "select   client_code,\n"
                + "         bank_branch_code,\n"
                + "         lhs_utility.get_name('client_code',client_code)client_name,\n"
                + "         tanno,\n"
                + "         lpad(last_gen_15g,9,0)last_gen_15g,\n"
                + "         lpad(last_gen_15h,9,0)last_gen_15h,\n"
                + "         lpad(next_gen_15g,9,0)next_gen_15g,\n"
                + "         lpad(next_gen_15h,9,0)next_gen_15h\n"
                + "    from (select rownum slno,\n"
                + "                       a.entity_code,\n"
                + "                       a.client_code,\n"
                + "                       a.client_name,\n"
                + "                       a.tanno,\n"
                + "                       a.bank_branch_code,\n"
                + "                       g15_flag,\n"
                + "                       nvl(g15_max_no, '0') last_gen_15g,\n"
                + "                       h15_flag,\n"
                + "                       nvl(h15_max_no, '0') last_gen_15h,\n"
                + "                       (nvl(g15_max_no, '0') + 1) next_gen_15g,\n"
                + "                       (nvl(h15_max_no, '0') + 1) next_gen_15h"
                + "            from (select a.entity_code,\n"
                + "                               a.acc_year,\n"
                + "                               a.quarter_no,\n"
                + "                               a.tds_type_code,\n"
                + "                               a.client_code,\n"
                + "                               a.client_name,\n"
                + "                               a.tanno,\n"
                + "                               A.bank_branch_code,\n"
                + "                         'G' g15_flag,\n"
                + "                         (select to_number(max(substr(reference_no, 2)))\n"
                + "                                  from deductee_mast_15gh b, client_mast c\n"
                + "                                 where c.entity_code = b.entity_code\n"
                + "                                   and c.client_code = b.client_code\n"
                + "                                   and c.entity_code = a.entity_code\n"
                + "                                   and (c.client_code = a.client_code or\n"
                + "                                       c.parent_code = a.client_code or\n"
                + "                                       c.g_parent_code = a.client_code or\n"
                + "                                       c.sg_parent_code = a.client_code or\n"
                + "                                       c.ssg_parent_code = a.client_code or\n"
                + "                                       c.sssg_parent_code = a.client_code)\n"
                + "                                   and b.entity_code = a.entity_code\n"
                + "                                   and b.acc_year = a.acc_year\n"
                + "                                   and b.tds_type_code = a.tds_type_code\n"
                + "                                   and bflag = 'B') g15_max_no,\n"
                + "                         'H' h15_flag,\n"
                + "                         (select to_number(max(substr(reference_no, 2)))\n"
                + "                                  from deductee_mast_15gh B, client_mast c\n"
                + "                                 where c.entity_code = b.entity_code\n"
                + "                                   and c.client_code = b.client_code\n"
                + "                                   and c.entity_code = a.entity_code\n"
                + "                                   and (c.client_code = a.client_code or\n"
                + "                                       c.parent_code = a.client_code or\n"
                + "                                       c.g_parent_code = a.client_code or\n"
                + "                                       c.sg_parent_code = a.client_code or\n"
                + "                                       c.ssg_parent_code = a.client_code or\n"
                + "                                       c.sssg_parent_code = a.client_code)\n"
                + "                                   and b.entity_code = a.entity_code\n"
                + "                                   and b.acc_year = a.acc_year\n"
                + "                                   and b.tds_type_code = a.tds_type_code\n"
                + "                                   and bflag = 'D') h15_max_no\n"
                + "                    from  (select '" + entity_code + "' entity_code,\n"
                + "                                       '" + acc_year + "' acc_year,\n"
                + "                                       '" + quarterNo + "' quarter_no,\n"
                + "                                       '" + tds_type_code + "' tds_type_code,\n"
                + "                                       a.client_code,\n"
                + "                                       a.client_name,\n"
                + "                                       a.tanno,\n"
                + "                                       a.bank_branch_code\n"
                + "                                  from client_mast a\n"
                + "                                 where entity_code = '" + entity_code + "'\n"
                + "                                   and ((" + process_level + " = 0 and code_level = " + code_level + " /*Login client code level*/\n"
                + "                                       and client_code = '" + genClientCode + "') or\n"
                + "                                       (" + process_level + " = 1 and code_level = " + (code_level + 1) + " /*Login client code level + 1*/\n"
                + "                                       ))\n"
                + "                                      \n"
                + "                                      --FILTER FOR LOGIN LEVEL START\n"
                + "                                   and a.client_code <> '" + genClientCode + "'\n"
                + "                                   and (a.client_code = '" + genClientCode + "' or\n"
                + "                                       a.parent_code = '" + genClientCode + "' or\n"
                + "                                       a.g_parent_code = '" + genClientCode + "' or\n"
                + "                                       a.sg_parent_code = '" + genClientCode + "' or\n"
                + "                                       a.ssg_parent_code = '" + genClientCode + "' or\n"
                + "                                       a.sssg_parent_code = '" + genClientCode + "')) a) a) a)";

        return query;

    }

    public String getReferenceNoDetails(String entity_code, String quarterNo, String acc_year, String tds_type_code, String genClientCode, int minVal, int maxVal,
            int process_level, int code_level) {

        String query = "select client_code,\n"
                + "         bank_branch_code,\n"
                + "         lhs_utility.get_name('client_code',client_code)client_name,\n"
                + "         tanno,\n"
                + "         lpad(last_gen_15g,9,0)last_gen_15g,\n"
                + "         lpad(last_gen_15h,9,0)last_gen_15h,\n"
                + "         lpad(next_gen_15g,9,0)next_gen_15g,\n"
                + "         lpad(next_gen_15h,9,0)next_gen_15h\n"
                + "    from (select rownum slno , a.entity_code,\n"
                + "                 a.client_code,\n"
                + "                 a.client_name,\n"
                + "                 a.tanno,\n"
                + "                 a.bank_branch_code,\n"
                + "                 g15_flag,\n"
                + "                 nvl(g15_max_no,'0')last_gen_15g,\n"
                + "                 'H' h15_flag,\n"
                + "                 nvl(h15_max_no,'0')last_gen_15h,\n"
                + "                 (nvl(g15_max_no,'0') + 1) next_gen_15g,\n"
                + "                 (nvl(h15_max_no,'0') + 1) next_gen_15h\n"
                + "            from (\n"
                + "            select       a.entity_code,\n"
                + "                         a.acc_year,\n"
                + "                         a.quarter_no,\n"
                + "                         a.tds_type_code,\n"
                + "                         a.client_code,\n"
                + "                         a.client_name,\n"
                + "                         a.tanno,\n"
                + "                         a.bank_branch_code,\n"
                + "                         'G' g15_flag,\n"
                + "                         (select to_number(max(substr(reference_no, 2)))\n"
                + "                            from deductee_mast_15gh b, client_mast c\n"
                + "                           where c.entity_code = b.entity_code\n"
                + "                           and c.client_code = b.client_code\n"
                + "                           and c.entity_code = a.entity_code\n"
                + "                           and (c.client_code = a.client_code or\n"
                + "                               c.parent_code = a.client_code or\n"
                + "                               c.g_parent_code = a.client_code or\n"
                + "                               c.sg_parent_code = a.client_code or\n"
                + "                               c.ssg_parent_code = a.client_code or\n"
                + "                               c.sssg_parent_code = a.client_code)\n"
                + "                             and b.entity_code = a.entity_code\n"
                + "                             and b.acc_year = a.acc_year\n"
                + "                              and b.tds_type_code = a.tds_type_code\n"
                + "                             and bflag = 'B') g15_max_no,\n"
                + "                         'H' h15_flag,\n"
                + "                         (select to_number(max(substr(reference_no, 2)))\n"
                + "                          from   deductee_mast_15gh b, client_mast c\n"
                + "                           where c.entity_code = b.entity_code\n"
                + "                           and c.client_code = b.client_code\n"
                + "                           and c.entity_code = a.entity_code\n"
                + "                           and (c.client_code = a.client_code or\n"
                + "                               c.parent_code = a.client_code or\n"
                + "                               c.g_parent_code = a.client_code or\n"
                + "                               c.sg_parent_code = a.client_code or\n"
                + "                               c.ssg_parent_code = a.client_code or\n"
                + "                               c.sssg_parent_code = a.client_code)\n"
                + "                           and b.entity_code = a.entity_code\n"
                + "                           and b.acc_year = a.acc_year\n"
                + "                           and b.tds_type_code = a.tds_type_code"
                + "                           and bflag = 'D') h15_max_no\n"
                + "                    from  (select '" + entity_code + "' entity_code,\n"
                + "                               '" + acc_year + "' acc_year,\n"
                + "                               '" + quarterNo + "' quarter_no,\n"
                + "                               '" + tds_type_code + "' tds_type_code,\n"
                + "                               a.client_code,\n"
                + "                               a.client_name,\n"
                + "                               a.tanno,\n"
                + "                               a.bank_branch_code\n"
                + "                          from client_mast a\n"
                + "                         where entity_code = '" + entity_code + "'\n"
                + "                           and ((" + process_level + " = 0 and code_level = " + code_level + " /*Login client code level*/\n"
                + "                               and client_code = '" + genClientCode + "') or\n"
                + "                               (" + process_level + " = 1 and code_level = " + (code_level + 1) + " /*Login client code level + 1*/\n"
                + "                               ))\n"
                + "                              \n"
                + "                              --FILTER FOR LOGIN LEVEL START\n"
                + "                           and a.client_code <> '" + genClientCode + "'\n"
                + "                           and (a.client_code = '" + genClientCode + "' or\n"
                + "                               a.parent_code = '" + genClientCode + "' or\n"
                + "                               a.g_parent_code = '" + genClientCode + "' or\n"
                + "                               a.sg_parent_code = '" + genClientCode + "' or\n"
                + "                               a.ssg_parent_code = '" + genClientCode + "' or\n"
                + "                               a.sssg_parent_code = '" + genClientCode + "')) a) a) a\n"
                + "                           where slno BETWEEN " + minVal + " AND " + maxVal + "\n";

        return query;

    }

    public String getFunctionString(String entity_code, String accYear, String quarterNo, String tdsTypeCode, String Bflag, String genClientCode, String nextGen15HNo) {
        String functionString
                = "select count(nvl(SUBSTR(t.reference_no, 2, 10), '0')) refranceNoCount\n"
                + "  from deductee_mast_15gh t\n"
                + " where t.entity_code = '" + entity_code + "'\n"
                + "   and t.acc_year = '" + accYear + "'\n"
                + "   and t.quarter_no = '" + quarterNo + "'\n"
                + "   and t.tds_type_code = '" + tdsTypeCode + "'\n"
                + "   and t.bflag = '" + Bflag + "'\n"
                + "   and exists\n"
                + " (select 1\n"
                + "          from client_mast w1\n"
                + "         where w1.client_code = t.client_code\n"
                + "           and (w1.client_code = '" + genClientCode + "' or w1.parent_code = '" + genClientCode + "' or\n"
                + "               w1.g_parent_code = '" + genClientCode + "' or\n"
                + "               w1.sg_parent_code = '" + genClientCode + "' or\n"
                + "               w1.ssg_parent_code = '" + genClientCode + "' or\n"
                + "               w1.sssg_parent_code = '" + genClientCode + "'))\n"
                + "   and t.reference_no = '" + nextGen15HNo + "'";

        return functionString;

    }

    public String getTempDataQuery(String l_entity_code, String accYear, String f_quarter_no, String tds_type_code, String TempleteCode, String GenClientCode) {

        String query = "delete from temp_data t where t.col1 = '" + l_entity_code + "' and t.col3 = '" + accYear + "'\n"
                + "and t.col5 = '" + f_quarter_no + "' and t.col8 = '" + tds_type_code + "' and t.col100 = '" + TempleteCode + "'"
                + "and exists (select 1 \n"
                + "                    from   client_mast w1\n"
                + "                    where  w1.client_code=t.col2\n"
                + "                    and    (w1.client_code='" + GenClientCode + "' or\n"
                + "                            w1.parent_code='" + GenClientCode + "' or\n"
                + "                            w1.g_parent_code='" + GenClientCode + "' or\n"
                + "                            w1.sg_parent_code='" + GenClientCode + "' or\n"
                + "                            w1.ssg_parent_code='" + GenClientCode + "' or\n"
                + "                            w1.sssg_parent_code='" + GenClientCode + "'))";

        return query;
    }

    Util utl;

    public Form15GHDB() {
        utl = new Util();
    }

}
